name: CI/CD
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install tic80
        run: |
          sudo apt update && sudo apt -y install build-essential cmake git libpipewire-0.3-dev libwayland-dev libsdl2-dev ruby-dev libcurl4-openssl-dev libglvnd-dev libglu1-mesa-dev freeglut3-dev
          git clone --recursive https://github.com/nesbox/TIC-80 && cd TIC-80/build
          cmake -DBUILD_SDLGPU=On -DBUILD_WITH_ALL=On -DBUILD_STATIC=On -DBUILD_PRO=On .. && cmake --build . --parallel
          sudo make install
      - name: export pet
        run: |
          tic80 --fs .  --cli --cmd="load pet/pet.fnl & export html pet/pet.fnl"
      - name: export shmp
        run: |
          tic80 --fs .  --cli --cmd="load shmp/shmp.fnl & export html shmp/shmp.fnl"
      - uses: actions/upload-artifact@v4
        with:
          name: pet-zip
          path: pet/pet.fnl.zip
      - uses: actions/upload-artifact@v4
        with:
          name: shmp-zip
          path: shmp/shmp.fnl.zip

  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      pet:  ${{ steps.filter.outputs.pet }}
      shmp: ${{ steps.filter.outputs.shmp }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pet:
              - 'pet/**'
            shmp:
              - 'shmp/**'

  deploy-pet:
    needs: 
      - build
      - changes
    if: ${{ github.ref_name == 'trunk' && needs.changes.outputs.pet == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: pet-zip
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: pet.fnl.zip
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: virtual-startup
          buildChannel: web
          buildNumber: ${{ github.sha }}

  deploy-shmp:
    needs:
      - build
      - changes
    if: ${{ github.ref_name == 'trunk' && needs.changes.outputs.shmp == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: shmp-zip
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: shmp.fnl.zip
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: fox-busters
          buildChannel: web
          buildNumber: ${{ github.sha }}
