name: CI/CD
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install tic80
        run: |
          wget https://github.com/nesbox/TIC-80/releases/download/v1.1.2837/tic80-v1.1-linux.deb
          sudo dpkg -i tic80-v1.1-linux.deb
      - name: export
        working-directory: pet
        run: |
          tic80 --fs . --cmd="export html pet.fnl alone=1" --cli


# env:
#   ITCH_USERNAME: my-username
#   ITCH_GAME_ID: my-game-id

  deploy:
    needs: build
    name: Upload to Itch
    runs-on: ubuntu-latest
    name: Deploy - Itch.io Web
    steps:
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: pet.fnl.zip
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: '4228853'
          buildChannel: web
          buildNumber: $VERSION
